server:
  port: 8080

security:
  user:
    password: user
  ignored: /,/favicon.ico,/index.html,/home.html,/dashboard.html,/js/**,/css/**,/webjars/**
  sessions: ALWAYS
management:
  security:
    role: HERO

logging:
  level:
    org.springframework.security: DEBUG
    com.netflix.discovery: 'OFF'

spring:
  oauth2:
    sso:
      loginPath: /dashboard/login
      logoutPath: /dashboard/logout

---
spring:
  profiles: default
  oauth2:
    client:
      clientId: 4632243d-8859-4229-82c3-bfe4955a408f
      clientSecret: ALAo6V-C76HjqUtrRHSAd0PO6URO26S8pmmaRbMjztx83lSwo3NkXqHoNLuWPLGNjidy9-_DXcXSk2WSGSEt9ws
      clientAuthenticationScheme: form
      accessTokenUri: https://authorize.smarthealthit.org/token
      userAuthorizationUri: https://authorize.smarthealthit.org/authorize
    resource:
      preferTokenInfo: false
      userInfoUri: https://authorize.smarthealthit.org/userinfo  


smarthealthit.sandbox.registration.access.token: eyJhbGciOiJSUzI1NiJ9.eyJhdWQiOlsiNDYzMjI0M2QtODg1OS00MjI5LTgyYzMtYmZlNDk1NWE0MDhmIl0sImlzcyI6Imh0dHBzOlwvXC9hdXRob3JpemUuc21hcnRoZWFsdGhpdC5vcmdcLyIsImp0aSI6IjQ1MjVjOTM3LTQ2ZGMtNDJmZi1hNmFjLTQyMmY5MTI3ZWNmNiIsImlhdCI6MTQ0MDQ0ODg3NX0.iuMvOU_IcW5OVhfvsEzCQCQGHhF2a0IuhWax7NCu2OVrCEFzJroVjyUMxfvM9azI2zZB5rM5y3ahMp18zJr1hDixp79SMSisacy367OitluOS-kRXnmpDxGxExLtkatZpjDdRdqRZLhGwoSQqOnE8AqiJe_0EZBCQq6SYxqrEa4  